const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.site-nav');toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false');}));
/* Native Wookiegrams feed: six local clips per view, with zero third-party embed overhead. */
(()=>{const feed=document.querySelector('[data-instagram-feed]');if(!feed)return;const refresh=document.querySelector('[data-feed-refresh]');const manifestPath='assets/instavids/manifest.json';let clips=[];
const shuffle=list=>{const pool=[...list];for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool};
const fallback=()=>{feed.innerHTML='<div class="instagram-placeholder"><span>INCOMING / WOOKIEGRAMS</span><strong>Fresh transmissions are being prepared.</strong></div>';};
const closeModal=modal=>{const player=modal.querySelector('video');player.pause();modal.remove();document.body.classList.remove('video-modal-open')};
const playClip=clip=>{const modal=document.createElement('div');modal.className='video-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label',clip.title||'Ghetto Wookie video');modal.innerHTML='<button class="video-modal-close" type="button" aria-label="Close video">×</button><div class="video-modal-player"></div>';const player=document.createElement('video');player.src=`assets/instavids/${clip.file}`;player.poster=`assets/instavids/${clip.poster}`;player.controls=true;player.autoplay=true;player.playsInline=true;modal.querySelector('.video-modal-player').append(player);modal.querySelector('.video-modal-close').addEventListener('click',()=>closeModal(modal));modal.addEventListener('click',event=>{if(event.target===modal)closeModal(modal)});document.addEventListener('keydown',function escape(event){if(event.key==='Escape'){closeModal(modal);document.removeEventListener('keydown',escape)}});document.body.classList.add('video-modal-open');document.body.append(modal);player.play().catch(()=>{})};
const render=()=>{if(!clips.length){fallback();return}feed.replaceChildren();shuffle(clips).slice(0,6).forEach((clip,index)=>{const card=document.createElement('article');card.className='instagram-video';card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Play ${clip.title||'Ghetto Wookie video'}`);const video=document.createElement('video');video.src=`assets/instavids/${clip.file}`;video.poster=`assets/instavids/${clip.poster}`;video.muted=true;video.loop=true;video.playsInline=true;video.preload='none';video.setAttribute('aria-hidden','true');card.classList.add('thumbnail-ready');card.addEventListener('pointerenter',()=>video.play().catch(()=>{}));card.addEventListener('pointerleave',()=>{video.pause();try{video.currentTime=.12}catch{}});card.addEventListener('click',()=>playClip(clip));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();playClip(clip)}});const meta=document.createElement('span');meta.className='instagram-video-meta';meta.innerHTML=`<b>${String(index+1).padStart(2,'0')} / WOOKIEGRAM</b><strong>${clip.title||'Incoming transmission'}</strong><i>Play transmission ↗</i>`;card.append(video,meta);feed.append(card)})};
fetch(manifestPath,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{clips=Array.isArray(data.videos)?data.videos.filter(v=>v&&v.file):[];render()}).catch(fallback);refresh?.addEventListener('click',render)})();
/* Homepage tour teaser: always surface the next three future invasions. */
(()=>{const dates=document.querySelector('[data-upcoming-dates]');if(!dates)return;
const itinerary=[
[2026,5,3,'MAY 03','Madison Square Garden · New York, USA'],[2026,5,7,'MAY 07','Hollywood Bowl · Los Angeles, USA'],[2026,5,11,'MAY 11','Wembley Stadium · London, UK'],[2026,5,15,'MAY 15','Tokyo Dome · Tokyo, Japan'],[2026,5,19,'MAY 19','Sydney Opera House · Sydney, Australia'],[2026,5,23,'MAY 23','Crater Funk Amphitheatre · Luna Trion-6'],[2026,5,27,'MAY 27','The Molten Ring · Io, Jovian System'],[2026,5,31,'MAY 31','The Echo Basilica · Abandoned Dyson Choirworld'],
[2026,6,4,'JUN 04','Red Rocks Amphitheatre · Colorado, USA'],[2026,6,8,'JUN 08','Maracanã Stadium · Rio de Janeiro, Brazil'],[2026,6,12,'JUN 12','Estádio do Morumbi · São Paulo, Brazil'],[2026,6,16,'JUN 16','Olympiastadion · Berlin, Germany'],[2026,6,20,'JUN 20','Stade de France · Paris, France'],[2026,6,24,'JUN 24','Funk Plateau · Titan'],[2026,6,27,'JUN 27','The Gravity Well Ballroom · Black Hole Perimeter · Stable Window'],[2026,6,30,'JUN 30','The Sporelight Pavilion · Mycelial Moon of Krrsh'],
[2026,7,3,'JUL 03','Slane Castle · Ireland'],[2026,7,7,'JUL 07','The Thousand-Beat Ziggurat · Drumma Kaan Origin Site'],[2026,7,11,'JUL 11','Soldier Field · Chicago, USA'],[2026,7,15,'JUL 15','BC Place · Vancouver, Canada'],[2026,7,19,'JUL 19','San Siro · Milan, Italy'],[2026,7,23,'JUL 23','Gocheok Sky Dome · Seoul, South Korea'],[2026,7,26,'JUL 26','Neon Tides Coliseum · Ocean World Pelagia'],[2026,7,30,'JUL 30','The Bone Spiral Arena · Ossuary Planet XN-9'],
[2026,8,2,'AUG 02','MetLife Stadium · New Jersey, USA'],[2026,8,6,'AUG 06','Camp Nou · Barcelona, Spain'],[2026,8,10,'AUG 10','Azadi Stadium · Tehran, Iran'],[2026,8,14,'AUG 14','FNB Stadium · Johannesburg, South Africa'],[2026,8,18,'AUG 18','The Chromatic Rift Stage · Light-Split Nebula'],[2026,8,21,'AUG 21','Orbital Groove Array · Low Earth Orbit · Unauthorized'],[2026,8,25,'AUG 25','SoFi Stadium · Los Angeles, USA'],[2026,8,29,'AUG 29','The Velvet Vacuum · Deep-Space Lounge Sector 7'],
[2026,9,3,'SEP 03','The O2 Arena · London, UK'],[2026,9,7,'SEP 07','Accor Arena · Paris, France'],[2026,9,11,'SEP 11','Krestovsky Stadium · Saint Petersburg, Russia'],[2026,9,15,'SEP 15','Foro Sol · Mexico City, Mexico'],[2026,9,19,'SEP 19','The Siren Halo · Trion-6 Upper Atmosphere'],[2026,9,22,'SEP 22','The Low-End Catacombs · Sub-Bass Civilization Ruins'],[2026,9,26,'SEP 26','NRG Stadium · Houston, USA'],[2026,9,30,'SEP 30','Time-Loop Court Alpha · DJ Astrognome Stronghold'],
[2026,10,31,'OCT 31','The Eternal Afterparty · Outside Linear Time']];
const today=new Date();today.setHours(0,0,0,0);
const future=itinerary.filter(([year,month,day])=>new Date(year,month-1,day)>today).slice(0,3);
if(!future.length){dates.textContent='No further Earth dates have been cleared for public release.';return}
dates.replaceChildren(...future.map(([, , ,label,venue])=>{const row=document.createElement('div'),date=document.createElement('b'),place=document.createElement('span');date.textContent=label;place.textContent=venue;row.append(date,place);return row;}));
})();